// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotchocgraphql;

#nullable disable

namespace hotchocgraphql.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20250905063506_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("hotchocgraphql.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LongDesc = "A ceramic mug perfect for hot beverages like coffee or tea.",
                            ShortDesc = "Coffee Mug"
                        },
                        new
                        {
                            Id = 2,
                            LongDesc = "A lined notebook for writing and note-taking.",
                            ShortDesc = "Notebook"
                        },
                        new
                        {
                            Id = 3,
                            LongDesc = "A compact wireless mouse with Bluetooth support.",
                            ShortDesc = "Wireless Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
